### ISSUE TITLE
How do I use the CSV in a spreadsheet?

### ISSUE THREAD

**Issue by therealzipy** [JustAHoax/Loonie-Tunes#2]
How do i impement the automatic information from the CSV to a spreadsheet to actually calculate profits automatically?

**Comment by JustAHoax** [comment]
Hi there, sorry for the delay. 
You would have to write some formulas that pull the appropriate information from the pricing that is within the CSV. Nothing is automatically calculated for profit, however the information in the CSV is the direct values needed to be able to achieve something like that.
