### ISSUE TITLE
Classic Support

### ISSUE THREAD

**Issue by rampaigewow** [JustAHoax/Loonie-Tunes#3]
Hi, is there anyway to have this work for WoW Classic / TBC? Why I point it to the AppData, it says it cannot find the realm list. So, I tried to "trick" it by changing the Classic Realm Name to one of the retail realm names...After that, It would allow me to select a realm, but would still say invalid format.

**Comment by JustAHoax** [comment]
Sorry for the delayed response.. 
I would have to rewrite some things for it to support Classic. It doesn't work with how you are "tricking" it since the realms are hard set and it tries to match up your realm choice with the app data from TSM. I could look into supporting Classic.
